//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppBiler.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bil", Namespace="http://schemas.datacontract.org/2004/07/BilService")]
    [System.SerializableAttribute()]
    public partial class Bil : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int antalDoorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bilNavnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfAppBiler.ServiceReference1.Motor motorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int antalDoors {
            get {
                return this.antalDoorsField;
            }
            set {
                if ((this.antalDoorsField.Equals(value) != true)) {
                    this.antalDoorsField = value;
                    this.RaisePropertyChanged("antalDoors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bilNavn {
            get {
                return this.bilNavnField;
            }
            set {
                if ((object.ReferenceEquals(this.bilNavnField, value) != true)) {
                    this.bilNavnField = value;
                    this.RaisePropertyChanged("bilNavn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfAppBiler.ServiceReference1.Motor motor {
            get {
                return this.motorField;
            }
            set {
                if ((object.ReferenceEquals(this.motorField, value) != true)) {
                    this.motorField = value;
                    this.RaisePropertyChanged("motor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Motor", Namespace="http://schemas.datacontract.org/2004/07/BilService")]
    [System.SerializableAttribute()]
    public partial class Motor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HKField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HK {
            get {
                return this.HKField;
            }
            set {
                if ((this.HKField.Equals(value) != true)) {
                    this.HKField = value;
                    this.RaisePropertyChanged("HK");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addBil", ReplyAction="http://tempuri.org/IService1/addBilResponse")]
        void addBil(WpfAppBiler.ServiceReference1.Bil bil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addBil", ReplyAction="http://tempuri.org/IService1/addBilResponse")]
        System.Threading.Tasks.Task addBilAsync(WpfAppBiler.ServiceReference1.Bil bil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAlleBils", ReplyAction="http://tempuri.org/IService1/getAlleBilsResponse")]
        WpfAppBiler.ServiceReference1.Bil[] getAlleBils();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAlleBils", ReplyAction="http://tempuri.org/IService1/getAlleBilsResponse")]
        System.Threading.Tasks.Task<WpfAppBiler.ServiceReference1.Bil[]> getAlleBilsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WpfAppBiler.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WpfAppBiler.ServiceReference1.IService1>, WpfAppBiler.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void addBil(WpfAppBiler.ServiceReference1.Bil bil) {
            base.Channel.addBil(bil);
        }
        
        public System.Threading.Tasks.Task addBilAsync(WpfAppBiler.ServiceReference1.Bil bil) {
            return base.Channel.addBilAsync(bil);
        }
        
        public WpfAppBiler.ServiceReference1.Bil[] getAlleBils() {
            return base.Channel.getAlleBils();
        }
        
        public System.Threading.Tasks.Task<WpfAppBiler.ServiceReference1.Bil[]> getAlleBilsAsync() {
            return base.Channel.getAlleBilsAsync();
        }
    }
}
